---
title: "RStudio + Blogdown + Github + Netlify = A winning formula"
date: "2017-12-29"
author: "Jamie Lendrum"
output: blogdown::html_page
tags: [r, rstudio, blogdown, git, github, netlify, blog, hugo]
---

I thought it was worth posting about how I set up this blog as I had enormous trouble setting it up. I'd never done anything like this before and so some Google searching exposed me to many different technologies, but I had no clue what they did, which were best/easiest to work with and which combination I needed to use them in.

First off, big thanks go to John Muschelli and his [YouTube video](https://www.youtube.com/watch?v=syWAKaj-4ck) which got me up and running in no time.

So if you want to go the route I have, you need several things installed on your machine:

* R
* RStudio
* The `blogdown` package (obtained via the usual `install.packages()` function)
* Git

You will also need accounts with Github and Netlify.

John's video explains how to go through the set-up process better than I can, but I do want to briefly explain my workflow (based on my limited understanding so far). To update my blog with a new post, these are the steps I take:

1. I create a new markdown file for a new blog post, and save it in my `r-house/content/post/` directory;
2. I rebuild my site on my local machine with the command `blogdown::build_site()`. This sets off the website generation software *Hugo* which sits behind `blogdown` to create the required HTML pages in the `r-house/public/` folder. The `public` folder holds all the files needed for the website.
3. I register these changes with Git on my local machine, by staging and committing these changes from within RStudio (Tools>Version Control>Commit);
4. I upload all of this to my GitHub repository by hitting the Push button.

That's it! Once my GitHub repository updates, Netlify automatically refreshes my blog by recognising the `public/` folder has changed.

My task now is to figure out how to use a different Hugo theme without breaking everything!

*UPDATE 2017-31-12*

Coming soon!...
